policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
        case: lower
        invalidLastCharacters: .
      gpg:
        required: true
      spellcheck:
        locale: US
      conventional:
        types:
          - feat
          - fix
          - build
          - chore
          - ci
          - docs
          - pref
          - refactor
          - style
          - test
        scopes:
          - flake
          - github
          - home
          - nixos
          - package
          - shell
          - gnome
          - niri
          - nushell
        descriptionLength: 72
