# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "hey-unstable-${version}";
  version = "2019-10-15";
  rev = "e409613c173703e3b5738559a877a0eefcc351e0";

  goPackagePath = "github.com/rakyll/hey";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/rakyll/hey.git";
    sha256 = "1blvlhis58a1hlsnb5zg0rmz1hfaji9agwpp9rxwmyp8vjczzp3k";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
