# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "703b5e6b11ae25aeb2af9ebb5d5fdf8fa2575211";
      sha256 = "0znpyz71gajx3g0j2zp63nhjj2c07g16885vxv4ykwnrfmzbgk4w";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/go-homedir";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/go-homedir";
      rev = "af06845cf3004701891bf4fdb884bfe4920b3727";
      sha256 = "0ydzkipf28hwj2bfxqmwlww47khyk6d152xax4bnyh60f4lq3nx1";
    };
  }
  {
    goPackagePath = "github.com/motemen/go-quickfix";
    fetch = {
      type = "git";
      url = "https://github.com/motemen/go-quickfix";
      rev = "5c522febc6796f9c2ceabf9374a75490e2d268da";
      sha256 = "0d4hnwy4wxqk2jfgi3lgib7jfd1xdh05fcfy6isck6n600dyxlka";
    };
  }
  {
    goPackagePath = "github.com/peterh/liner";
    fetch = {
      type = "git";
      url = "https://github.com/peterh/liner";
      rev = "6f820f8f90ce9482ffbd40bb15f9ea9932f4942d";
      sha256 = "1cvar55nhab06z70p3bgsqyls1kmyprc4qa9i0sc8sj0abv6rn0a";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "342b2e1fbaa52c93f31447ad2c6abc048c63e475";
      sha256 = "0flv9idw0jm5nm8lx25xqanbkqgfiym6619w575p7nrdh0riqwqh";
    };
  }
  {
    goPackagePath = "golang.org/x/tools";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/tools";
      rev = "e377ae9d63860e3b8f606b92a1a7c7df5b14ca67";
      sha256 = "11yxv5wyd821q5la1n978z1wpkrqjdxmkshz5rhrzzgnylssvdqw";
    };
  }
]
