---
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16

      - uses: cachix/cachix-action@v10
        with:
          name: terlar
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community
      - name: Enable incremental cache upload
        run: cachix watch-store terlar &

      - name: Check
        run: nix flake check --print-build-logs
