---
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v16

      - uses: cachix/cachix-action@v10
        with:
          name: terlar
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Enable incremental cache upload
        run: cachix watch-store terlar &

      - name: Check flake
        run: nix flake check

  build-home-configuration:
    strategy:
      matrix:
        include:
          - username: terje
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v16

      - uses: cachix/cachix-action@v10
        with:
          name: terlar
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Enable incremental cache upload
        run: cachix watch-store terlar &

      - name: Build activation package
        run: |
          nix build --print-build-logs .#homeConfigurations.${{ matrix.username }}.activationPackage

  build-nixos-configuration:
    strategy:
      matrix:
        host:
          - beetle
          - kong
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v16

      - uses: cachix/cachix-action@v10
        with:
          name: terlar
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Enable incremental cache upload
        run: cachix watch-store terlar &

      - name: Build system
        run: |
          nix build --print-build-logs .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
