name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  changes:
    name: Changes
    runs-on: ubuntu-latest
    outputs:
      nixos-configuration: ${{ steps.changes.outputs.nixos-configuration }}
      home-configuration: ${{ steps.changes.outputs.home-configuration }}
      installer-yubikey: ${{ steps.changes.outputs.installer-yubikey }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Path filters
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4
        id: changes
        with:
          filters: |
            nixos-configuration:
              - flake.nix
              - flake.lock
              - 'configurations/nixos/**'
              - 'modules/nixos/**'
              - 'modules/home/**'
            home-configuration:
              - flake.nix
              - flake.lock
              - 'configurations/home/**'
              - 'modules/home/**'
            installer-yubikey:
              - flake.nix
              - flake.lock
              - 'configurations/nixos/installer-yubikey/**'
              - 'packages/drduh-gpg-conf/**'
              - 'packages/drduh-yubikey-guide/**'
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install Nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31
        with:
          install_url: https://releases.nixos.org/nix/nix-2.33.0/install
      - name: Nix cache (cachix)
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          useDaemon: true
          name: terlar
          extraPullNames: cuda-maintainers
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run check
        run: nix flake check
  build-home-configuration:
    name: Build home configuration
    needs: changes
    if: ${{ needs.changes.outputs.home-configuration == 'true' }}
    strategy:
      matrix:
        include:
          - username: terje
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install Nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31
        with:
          install_url: https://releases.nixos.org/nix/nix-2.33.0/install
      - name: Nix cache (cachix)
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          useDaemon: true
          name: terlar
          extraPullNames: cuda-maintainers
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build activation package
        run: |
          nix build --print-build-logs .#homeConfigurations.${{ matrix.username }}.activationPackage
  build-nixos-configuration:
    name: Build NixOS configuration
    needs: changes
    if: ${{ needs.changes.outputs.nixos-configuration == 'true' }}
    strategy:
      matrix:
        host:
          - kong
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      - name: Install Nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31
        with:
          install_url: https://releases.nixos.org/nix/nix-2.33.0/install
      - name: Nix cache (cachix)
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          useDaemon: true
          name: terlar
          extraPullNames: cuda-maintainers
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build system
        run: |
          nix build --print-build-logs .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
  build-iso:
    name: Build ISO
    needs: changes
    if: ${{ needs.changes.outputs.installer-yubikey == 'true' }}
    strategy:
      matrix:
        name:
          - installer-yubikey
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install Nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31
        with:
          install_url: https://releases.nixos.org/nix/nix-2.33.0/install
      - name: Nix cache (cachix)
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          useDaemon: true
          name: terlar
          extraPullNames: cuda-maintainers
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - name: Build ISO
        run: |
          GC_DONT_GC=1 nix build --print-build-logs .#nixosConfigurations.${{ matrix.name }}.config.system.build.isoImage
