---
name: Update flake.lock

on:
  schedule:
    - cron: '0 8 * * 0'
  workflow_dispatch:

jobs:
  flake-lock-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v13
        with:
          nix-package-url: https://releases.nixos.org/nix/nix-2.18.2/nix-2.18.2-x86_64-linux.tar.xz
          diagnostic-endpoint: ''

      - uses: tibdex/github-app-token@v2.1.0
        id: generate-app-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v23
        with:
          token: ${{ steps.generate-app-token.outputs.token }}
          branch: update-flake-lock
          commit-msg: "chore(flake): update flake.lock"
          pr-title: "chore(flake): update flake.lock"
          pr-labels: |
            chore
            flake
            automation

  dev-flake-lock-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v13
        with:
          nix-package-url: https://releases.nixos.org/nix/nix-2.18.2/nix-2.18.2-x86_64-linux.tar.xz
          diagnostic-endpoint: ''

      - uses: tibdex/github-app-token@v2.1.0
        id: generate-app-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update dev/flake.lock
        uses: DeterminateSystems/update-flake-lock@v23
        with:
          path-to-flake-dir: dev/
          token: ${{ steps.generate-app-token.outputs.token }}
          branch: update-dev-flake-lock
          commit-msg: "chore(flake): update dev/flake.lock"
          pr-title: "chore(flake): update dev/flake.lock"
          pr-labels: |
            chore
            flake
            automation
