---
name: Update inputs

on:
  schedule:
    - cron: '0 8 * * 0'
  workflow_dispatch:

jobs:
  update_inputs:
    name: Update inputs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Nix
      uses: cachix/install-nix-action@v15

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Update inputs
      run: |
        nix flake update --commit-lock-file

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Update flake inputs"
        branch: "automation/update-flake-inputs"
        delete-branch: true
        labels: |
          chore
          inputs
          automated
